# Generated by Django 3.0 on 2020-02-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
