# Generated by Django 2.2.6 on 2019-11-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('times_sold', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='media/images/items')),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
