# Generated by Django 2.2.6 on 2019-11-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('general', 'GENERAL'), ('supplments', 'SUPPLMENTS'), ('pain killers', 'PAIN KILLERS'), ('cold-cough', 'COLD-COUGH'), ('stomach', 'STOMACH'), ('skin-care', 'SKIN-CARE'), ('hair-care', 'HAIR-CARE')], default='general', max_length=25),
        ),
    ]
