# Generated by Django 3.0 on 2020-02-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200209_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
