# Generated by Django 3.0 on 2020-02-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20200211_2346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
